//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animlist_Transition_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Animlist_Transition_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#0106&quot; class=&quot;hkbBehaviorGraphStringData&quot; signature=&quot;0xc713064e&quot;&gt;
        ///			&lt;hkparam name=&quot;eventNames&quot; numelements=&quot;1217&quot;&gt;
        ///				&lt;hkcstring&gt;FootLeft&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;FootRight&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;WeapEquip&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;na_MRh_BeginCast_Event&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;MRh_Cast_State_to_MRh_Readied_State&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;MRh_Standing_Cast_State_to_MRh_Moving_Cast_State&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;MRh_SpellReady_Event&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;MRh_Spe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0106 {
            get {
                return ResourceManager.GetString("_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#0107&quot; class=&quot;hkbVariableValueSet&quot; signature=&quot;0x27812d8d&quot;&gt;
        ///			&lt;hkparam name=&quot;wordVariableValues&quot; numelements=&quot;230&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;value&quot;&gt;0&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;value&quot;&gt;0&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;value&quot;&gt;0&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;value&quot;&gt;0&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;value&quot;&gt;1118103680&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0107 {
            get {
                return ResourceManager.GetString("_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#0108&quot; class=&quot;hkbBehaviorGraphData&quot; signature=&quot;0x95aca5d&quot;&gt;
        ///			&lt;hkparam name=&quot;attributeDefaults&quot; numelements=&quot;0&quot;&gt;&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;variableInfos&quot; numelements=&quot;230&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;role&quot;&gt;
        ///						&lt;hkobject&gt;
        ///							&lt;hkparam name=&quot;role&quot;&gt;ROLE_DEFAULT&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;flags&quot;&gt;0&lt;/hkparam&gt;
        ///						&lt;/hkobject&gt;
        ///					&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;type&quot;&gt;VARIABLE_TYPE_REAL&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;role&quot;&gt;
        ///						&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0108 {
            get {
                return ResourceManager.GetString("_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#0340&quot; class=&quot;hkbStateMachine&quot; signature=&quot;0x816c1dcb&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;0&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;RootBehaviorGraph&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;eventToSendWhenStateOrTransitionChanges&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;id&quot;&gt;-1&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;payload&quot;&gt;null&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///			&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;startStateChooser&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;startStateId&quot;&gt;14&lt;/hkparam&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _0340 {
            get {
                return ResourceManager.GetString("_0340", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#2378&quot; class=&quot;hkbStateMachineTransitionInfoArray&quot; signature=&quot;0xe397b11e&quot;&gt;
        ///			&lt;hkparam name=&quot;transitions&quot; numelements=&quot;4&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;triggerInterval&quot;&gt;
        ///						&lt;hkobject&gt;
        ///							&lt;hkparam name=&quot;enterEventId&quot;&gt;-1&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;exitEventId&quot;&gt;-1&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;enterTime&quot;&gt;0.000000&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;exitTime&quot;&gt;0.000000&lt;/hkparam&gt;
        ///						&lt;/hkobject&gt;
        ///					&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;initiateInterval&quot;&gt;
        ///						&lt;hkobject&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2378 {
            get {
                return ResourceManager.GetString("_2378", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#2517&quot; class=&quot;hkbModifierList&quot; signature=&quot;0xa4180ca1&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;1&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;RootModifierList&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;enable&quot;&gt;true&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;modifiers&quot; numelements=&quot;6&quot;&gt;
        ///				#2516
        ///				#2514
        ///				#0208
        ///				#0206
        ///				#2512
        ///				#2510
        ///&lt;!-- MOD_CODE ~testfl~ OPEN --&gt;
        ///				{0}
        ///&lt;!-- CLOSE --&gt;
        ///			&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string _2517 {
            get {
                return ResourceManager.GetString("_2517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap av_werewolf {
            get {
                object obj = ResourceManager.GetObject("av_werewolf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;BSIsActiveModifier&quot; signature=&quot;0xb0fde45a&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;{1}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;2&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{2}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;enable&quot;&gt;true&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;bIsActive0&quot;&gt;false&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;bInvertActive0&quot;&gt;false&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;bIsActive1&quot;&gt;false&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;bInvertActive1&quot;&gt;false&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;bIsActive2&quot;&gt;false&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSIsActiveModifier {
            get {
                return ResourceManager.GetString("BSIsActiveModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#0029&quot; class=&quot;hkbCharacterStringData&quot; signature=&quot;0x655b42bc&quot;&gt;
        ///			&lt;hkparam name=&quot;deformableSkinNames&quot; numelements=&quot;0&quot;&gt;&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;rigidSkinNames&quot; numelements=&quot;0&quot;&gt;&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;animationNames&quot; numelements=&quot;{0}&quot;&gt;
        ///				&lt;hkcstring&gt;Animations\1HM_1stP_Run.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;Animations\1hm_1stP_Walk.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;Animations\1HM_AttackForwardSprint.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;Animations\1HM_AttackLeft.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string f_0029 {
            get {
                return ResourceManager.GetString("f#0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbVariableBindingSet&quot; signature=&quot;0x338ad4ff&quot;&gt;
        ///			&lt;hkparam name=&quot;bindings&quot; numelements=&quot;1&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;memberPath&quot;&gt;bIsActive0&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;variableIndex&quot;&gt;81&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;bitIndex&quot;&gt;-1&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;bindingType&quot;&gt;BINDING_TYPE_VARIABLE&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///			&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;indexOfBindingToEnable&quot;&gt;-1&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkbActiveVariableBindingSet {
            get {
                return ResourceManager.GetString("hkbActiveVariableBindingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbBlendingTransitionEffect&quot; signature=&quot;0xfd8584fe&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;{1}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;0&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{2}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;selfTransitionMode&quot;&gt;SELF_TRANSITION_MODE_CONTINUE&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;eventMode&quot;&gt;EVENT_MODE_PROCESS_ALL&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;duration&quot;&gt;{3}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;toGeneratorStartTimeFraction&quot;&gt;0.000000&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;flags&quot;&gt;0&lt;/hkparam&gt;
        ///			&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hkbBlendingTransitionEffect {
            get {
                return ResourceManager.GetString("hkbBlendingTransitionEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbClipGenerator&quot; signature=&quot;0x333b85b9&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;{1}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;0&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{2}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;animationName&quot;&gt;{3}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;triggers&quot;&gt;{4}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;cropStartAmountLocalTime&quot;&gt;{5}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;cropEndAmountLocalTime&quot;&gt;{6}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;startTime&quot;&gt;{7}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;playbackSpeed&quot;&gt;{8}&lt;/hkparam&gt;
        ///			&lt;hkp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hkbClipGenerator {
            get {
                return ResourceManager.GetString("hkbClipGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbEvaluateExpressionModifier&quot; signature=&quot;0xf900f6be&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;2&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{1}_DefaultFloatModifier&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;enable&quot;&gt;true&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;expressions&quot;&gt;{2}&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkbEvaluateExpressionModifier {
            get {
                return ResourceManager.GetString("hkbEvaluateExpressionModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbExpressionDataArray&quot; signature=&quot;0x4b9ee1a2&quot;&gt;
        ///			&lt;hkparam name=&quot;expressionsData&quot; numelements=&quot;1&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;expression&quot;&gt;{1}_AnimationSpeed = 1.0&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;assignmentVariableIndex&quot;&gt;-1&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;assignmentEventIndex&quot;&gt;-1&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;eventMode&quot;&gt;EVENT_MODE_SEND_ONCE&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///			&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkbExpressionDataArray {
            get {
                return ResourceManager.GetString("hkbExpressionDataArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbModifierGenerator&quot; signature=&quot;0x1f81fae6&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;1&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{1}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;modifier&quot;&gt;{2}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;generator&quot;&gt;{3}&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkbModifierGenerator {
            get {
                return ResourceManager.GetString("hkbModifierGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbStateMachine&quot; signature=&quot;0x816c1dcb&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;userData&quot;&gt;0&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{1}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;eventToSendWhenStateOrTransitionChanges&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;id&quot;&gt;-1&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;payload&quot;&gt;null&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///			&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;startStateChooser&quot;&gt;null&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;startStateId&quot;&gt;0&lt;/hkparam&gt;
        ///			&lt;hkparam name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hkbStateMachine {
            get {
                return ResourceManager.GetString("hkbStateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbStateMachineEventPropertyArray&quot; signature=&quot;0xb07b4388&quot;&gt;
        ///			&lt;hkparam name=&quot;events&quot; numelements=&quot;{1}&quot;&gt;
        ///{2}
        ///			&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkbStateMachineEventPropertyArray {
            get {
                return ResourceManager.GetString("hkbStateMachineEventPropertyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbStateMachineStateInfo&quot; signature=&quot;0xed7f9d0&quot;&gt;
        ///			&lt;hkparam name=&quot;variableBindingSet&quot;&gt;{1}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;listeners&quot; numelements=&quot;0&quot;&gt;&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;enterNotifyEvents&quot;&gt;{2}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;exitNotifyEvents&quot;&gt;{3}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;transitions&quot;&gt;{4}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;generator&quot;&gt;{5}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;name&quot;&gt;{6}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;stateId&quot;&gt;{7}&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;probability&quot;&gt;1.000000&lt;/hkparam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hkbStateMachineStateInfo {
            get {
                return ResourceManager.GetString("hkbStateMachineStateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbStateMachineTransitionInfoArray&quot; signature=&quot;0xe397b11e&quot;&gt;
        ///			&lt;hkparam name=&quot;transitions&quot; numelements=&quot;{1}&quot;&gt;
        ///{2}
        ///			&lt;/hkparam&gt;
        ///		&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkbTransitionInfoArray {
            get {
                return ResourceManager.GetString("hkbTransitionInfoArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;{0}&quot; class=&quot;hkbVariableBindingSet&quot; signature=&quot;0x338ad4ff&quot;&gt;
        ///			&lt;hkparam name=&quot;bindings&quot; numelements=&quot;4&quot;&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;memberPath&quot;&gt;cropStartAmountLocalTime&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;variableIndex&quot;&gt;$variableID[{1}]$&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;bitIndex&quot;&gt;-1&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;bindingType&quot;&gt;BINDING_TYPE_VARIABLE&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;memberPath&quot;&gt;cropEndAmountLocalTime&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;variableInd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hkbVariableBindingSet {
            get {
                return ResourceManager.GetString("hkbVariableBindingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;id&quot;&gt;{0}&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;payload&quot;&gt;{1}&lt;/hkparam&gt;
        ///				&lt;/hkobject&gt;
        ///.
        /// </summary>
        internal static string hkEventProperty {
            get {
                return ResourceManager.GetString("hkEventProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 				&lt;hkobject&gt;
        ///					&lt;hkparam name=&quot;triggerInterval&quot;&gt;
        ///						&lt;hkobject&gt;
        ///							&lt;hkparam name=&quot;enterEventId&quot;&gt;-1&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;exitEventId&quot;&gt;-1&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;enterTime&quot;&gt;0.000000&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;exitTime&quot;&gt;0.000000&lt;/hkparam&gt;
        ///						&lt;/hkobject&gt;
        ///					&lt;/hkparam&gt;
        ///					&lt;hkparam name=&quot;initiateInterval&quot;&gt;
        ///						&lt;hkobject&gt;
        ///							&lt;hkparam name=&quot;enterEventId&quot;&gt;-1&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;exitEventId&quot;&gt;-1&lt;/hkparam&gt;
        ///							&lt;hkparam name=&quot;enterTime&quot;&gt;0.000000&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hkTransitionInfo {
            get {
                return ResourceManager.GetString("hkTransitionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;hkobject name=&quot;#0029&quot; class=&quot;hkbCharacterStringData&quot; signature=&quot;0x655b42bc&quot;&gt;
        ///			&lt;hkparam name=&quot;deformableSkinNames&quot; numelements=&quot;0&quot;&gt;&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;rigidSkinNames&quot; numelements=&quot;0&quot;&gt;&lt;/hkparam&gt;
        ///			&lt;hkparam name=&quot;animationNames&quot; numelements=&quot;{0}&quot;&gt;
        ///				&lt;hkcstring&gt;Animations\1HM_1stP_Run.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;Animations\1hm_1stP_Walk.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;Animations\1HM_AttackForwardSprint.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcstring&gt;Animations\1HM_AttackLeft.hkx&lt;/hkcstring&gt;
        ///				&lt;hkcst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string m_0029 {
            get {
                return ResourceManager.GetString("m_0029", resourceCulture);
            }
        }
    }
}
